### ISSUE TITLE
Doesn't work with Ren'Py v7.4.0.1028

### ISSUE THREAD

**Issue by kyouryuukunn** [Enerccio/renpy-debugger#2]
This doesn't work correctly with Ren'Py v7.4.0.1028.
I tested windows 10 & ubuntu.20.04.1

This is error code.

Resetting cache.
Resetting cache.
Resetting cache.
Exception in thread DAP:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "debugger.py", line 55, in run
File "/usr/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

**Comment by Enerccio** [comment]
Is something block your 14711 port?

**Comment by kyouryuukunn** [comment]
I used lsof command.

lsof -i:14711
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
python  7174 kuma    5u  IPv4  60873      0t0  TCP *:14711 (LISTEN)

I copied librpydb, debugger.py, 0000_debugger.rpy into the_question in v7.4.0.1028.
I changed the port from 14711 to 14712 in librpydb/baseconf.py.
Then an error message didn't show, but the lancher didn't open the_question.

**Comment by kyouryuukunn** [comment]
Sorry, Enerccio.

I missed manual. I used "connect" by debugger then the game window was opened.

And I have another question about v #.
I was in line 452 where camera_check_points was defined and tried to display variable camera_check_points by using "v camera_check_points".
But below error was displayed.
I understood that "v #" means # is variable name, but it is wrong?

```
>>> v camera_check_points

Failed to get variable, check syntax
>>>
```

![image](https://user-images.githubusercontent.com/1556311/100764738-044f8580-343a-11eb-8735-ce59e611efe6.png)

**Comment by Enerccio** [comment]
You choose the variables by variable ID that is listed by `scopes` command. Ie `v 0` or `v 1`

**Comment by kyouryuukunn** [comment]
Thank you, Enerccio.
It was worked.

Didn't you sent pull request to PyTom?
I think this functions is wanted by many Ren'Py users.

**Comment by Enerccio** [comment]
It is but pytom didn't like it (but maybe his mind would be changed? I dunno). I was working on gui debugger in renpy "game" itself but ran into performance issues. I wish I could do like intellij integration but that might be quite the undertaking.

**Comment by kyouryuukunn** [comment]
OK.

Thank you for good library.

**Comment by Enerccio** [comment]
No problem. Honestly a lot of ren'py developers have very simple loops and don't need the debugger (prints are enough). But I was working on rpg that needed lot of code for combat loops and such so I needed it lol.
